// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.NewCliFeatures.SQLite
{
	[Table("TEST_T4_CASING")]
	public class TestT4Casing
	{
		[Column("ALL_CAPS"             )] public int AllCaps             { get; internal set; } // INT
		[Column("CAPS"                 )] public int Caps                { get; internal set; } // INT
		[Column("PascalCase"           )] public int PascalCase          { get; internal set; } // INT
		[Column("Pascal_Snake_Case"    )] public int PascalSnakeCase     { get; internal set; } // INT
		[Column("PascalCase_Snake_Case")] public int PascalCaseSnakeCase { get; internal set; } // INT
		[Column("snake_case"           )] public int SnakeCase           { get; internal set; } // INT
		[Column("camelCase"            )] public int CamelCase           { get; internal set; } // INT
	}
}
