using System;
using System.Diagnostics.CodeAnalysis;

using LinqToDB.Internal.Linq.Builder;
using LinqToDB.Internal.SqlQuery;
using LinqToDB.Mapping;

namespace LinqToDB
{
	public partial class Sql
	{
		/// <summary>
		/// Placeholder for a generated SQL identifier of a table source registered with
		/// <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.
		/// </summary>
		/// <remarks>
		/// LinqToDB assigns provider-specific aliases to table sources during SQL generation, and
		/// the emitted table name can also come from mapping or table-name overrides. A <c>SqlID</c>
		/// lets hint and custom SQL APIs refer to those generated identifiers without hard-coding
		/// provider output.
		/// <para>
		/// APIs that can use <c>SqlID</c> values include provider hint methods with <c>Sql.SqlID</c>
		/// parameters, such as MySQL and PostgreSQL <c>SubQueryTableHint(...)</c>, SQL Server
		/// <c>OptionTableHint(...)</c>, Oracle/MySQL optimizer hints that target specific table references,
		/// and format-parameter hint APIs such as ClickHouse <c>SettingsHint(...)</c>.
		/// </para>
		/// </remarks>
		public readonly struct SqlID : IToSqlConverter, IEquatable<SqlID>
		{
			/// <summary>
			/// Kind of generated identifier to resolve.
			/// </summary>
			public SqlIDType Type { get; }

			/// <summary>
			/// Logical table source identifier assigned by <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.
			/// </summary>
			public string    ID   { get; }

			/// <summary>
			/// Creates a generated SQL identifier placeholder.
			/// </summary>
			/// <param name="type">Kind of generated identifier to resolve.</param>
			/// <param name="id">Logical table source identifier assigned by <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.</param>
			public SqlID(SqlIDType type, string id)
			{
				ID   = id;
				Type = type;
			}

			public override string ToString()
			{
				return $"{Type}:{ID}";
			}

			public override bool Equals([NotNullWhen(true)] object? obj)
			{
				return obj is SqlID other && Equals(other);
			}

			public bool Equals(SqlID other)
			{
				return Type == other.Type && string.Equals(ID, other.ID, StringComparison.Ordinal);
			}

			public override int GetHashCode()
			{
				return HashCode.Combine(Type, ID);
			}

			public ISqlExpression ToSql(object value)
			{
				return new SqlValue(typeof(SqlID), value);
			}

			public static SqlID Parse(string value)
			{
				var idx = value.IndexOf(':', StringComparison.Ordinal);

				if (idx == -1)
					throw new InvalidOperationException($"Cannot parse '{value}' to SqlID.");

				var type = value.Substring(0, idx);
				var id   = value.Substring(idx + 1);

#if NET8_0_OR_GREATER
				return new (Enum.Parse<SqlIDType>(type), id);
#else
				return new ((SqlIDType)Enum.Parse(typeof(SqlIDType), type), id);
#endif
			}
		}

		/// <summary>
		/// Creates a placeholder that resolves to the generated SQL table alias for the table source.
		/// </summary>
		/// <param name="id">Logical table source identifier assigned by <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.</param>
		/// <returns><see cref="SqlID"/> configured with <see cref="SqlIDType.TableAlias"/>.</returns>
		/// <remarks>
		/// Use when a hint or SQL extension must reference the alias generated by LinqToDB for a table source.
		/// The table source must be marked in the query with <c>TableID(...)</c> using the same
		/// logical id before this placeholder can be resolved. See also <c>Sql.TableName</c> and
		/// <c>Sql.TableSpec</c>.
		/// </remarks>
		public static SqlID TableAlias(string id)
		{
			return new(SqlIDType.TableAlias, id);
		}

		/// <summary>
		/// Creates a placeholder that resolves to the generated SQL table name for the table source.
		/// </summary>
		/// <param name="id">Logical table source identifier assigned by <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.</param>
		/// <returns><see cref="SqlID"/> configured with <see cref="SqlIDType.TableName"/>.</returns>
		/// <remarks>
		/// Use when a hint or SQL extension must reference the provider-rendered table name instead of the
		/// generated alias. The name can originate from mapping or table-name overrides.
		/// The table source must be marked in the query with <c>TableID(...)</c> using the same
		/// logical id before this placeholder can be resolved. See also <c>Sql.TableAlias</c> and
		/// <c>Sql.TableSpec</c>.
		/// </remarks>
		public static SqlID TableName(string id)
		{
			return new(SqlIDType.TableName, id);
		}

		/// <summary>
		/// Creates a placeholder that resolves to the generated SQL table specification/path for the table source.
		/// </summary>
		/// <param name="id">Logical table source identifier assigned by <see cref="LinqExtensions.TableID{T}(ITable{T}, string?)"/>.</param>
		/// <returns><see cref="SqlID"/> configured with <see cref="SqlIDType.TableSpec"/>.</returns>
		/// <remarks>
		/// Use when a hint or SQL extension must reference the SQL builder's full table source path instead
		/// of only the alias or rendered table name. The table source must be marked in the query with
		/// <c>TableID(...)</c> using the same logical id before this placeholder can be resolved.
		/// See also <c>Sql.TableAlias</c> and <c>Sql.TableName</c>.
		/// </remarks>
		public static SqlID TableSpec(string id)
		{
			return new(SqlIDType.TableSpec, id);
		}
	}
}
