// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.All.SQLiteNorthwind
{
	[Table("Current Product List", IsView = true)]
	public class CurrentProductList
	{
		[Column("ProductID"  , DataType  = DataType.Int32, DbType   = "INT"                                                 )] public int    ProductId   { get; set; } // INT
		[Column("ProductName", CanBeNull = false         , DataType = DataType.NVarChar, DbType = "varchar(40)", Length = 40)] public string ProductName { get; set; } = null!; // varchar(40)
	}
}
