using System.Collections.Generic;
using System.Text;

using LinqToDB;
using LinqToDB.DataProvider.Oracle;
using LinqToDB.Internal.DataProvider;
using LinqToDB.Internal.SqlProvider;
using LinqToDB.Internal.SqlQuery;
using LinqToDB.Mapping;

using NUnit.Framework;

using Shouldly;

namespace Tests.DataProvider
{
	[TestFixture]
	public class OracleSqlBuilderTests
	{
		[Table("Issue1879Table")]
		sealed class Issue1879Table
		{
			[PrimaryKey, Identity]
			public int Id { get; set; }

			[Column]
			public int Value { get; set; }
		}

		[Test]
		public void Issue1879CreateTableUsesNativeIdentityForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlCreateTableStatement(table));

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("GENERATED BY DEFAULT AS IDENTITY");
			sql[0].ShouldNotContain("SIDENTITY_");
			sql[0].ShouldNotContain("TIDENTITY_");
		}

		[Test]
		public void Issue1879CreateTableKeepsSequenceIdentityForOracle11()
		{
			var sql = BuildSql(OracleVersion.v11, table => new SqlCreateTableStatement(table));

			sql.Count.ShouldBe(3);
			sql[0].ShouldNotContain("GENERATED BY DEFAULT AS IDENTITY");
			sql[1].ShouldContain("CREATE SEQUENCE \"SIDENTITY_Issue1879Table\"");
			sql[2].ShouldContain("CREATE OR REPLACE TRIGGER \"TIDENTITY_Issue1879Table\"");
		}

		[Test]
		public void Issue1879DropTableDoesNotDropSequenceOrTriggerForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlDropTableStatement(table));

			sql.ShouldBe(new[] { "DROP TABLE \"Issue1879Table\"" });
		}

		[Test]
		public void Issue1879TruncateResetsNativeIdentityForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlTruncateTableStatement
			{
				Table         = table,
				ResetIdentity = true,
			});

			sql.ShouldBe(new[]
			{
				"TRUNCATE TABLE \"Issue1879Table\"",
				"ALTER TABLE \"Issue1879Table\" MODIFY (\"Id\" GENERATED BY DEFAULT AS IDENTITY (START WITH 1))",
			});
		}

		static IReadOnlyList<string> BuildSql(OracleVersion version, System.Func<SqlTable, SqlStatement> createStatement)
		{
			var provider  = OracleTools.GetDataProvider(version, OracleProvider.Managed);
			var options   = new DataOptions();
			var optimizer = provider.GetSqlOptimizer(options);
			var factory   = optimizer.CreateSqlExpressionFactory(provider.MappingSchema, options);
			var context   = new OptimizationContext(
				new EvaluationContext(),
				options,
				provider.SqlProviderFlags,
				provider.MappingSchema,
				optimizer.CreateOptimizerVisitor(false),
				optimizer.CreateConvertVisitor(false),
				factory,
				false,
				true,
				static () => NoopQueryParametersNormalizer.Instance);
			var builder   = provider.CreateSqlBuilder(provider.MappingSchema, options);
			var table     = new SqlTable(provider.MappingSchema.GetEntityDescriptor(typeof(Issue1879Table)));
			var statement = createStatement(table);
			var commands  = new List<string>();

			for (var commandNumber = 0; commandNumber < builder.CommandCount(statement); commandNumber++)
			{
				var sql = new StringBuilder();
				builder.BuildSql(commandNumber, statement, sql, context, new AliasesContext(), null);
				commands.Add(sql.ToString().Trim());
			}

			return commands;
		}
	}
}
