using System;
using System.Collections.Generic;
using System.Text;

using LinqToDB;
using LinqToDB.DataProvider.Oracle;
using LinqToDB.Internal.DataProvider;
using LinqToDB.Internal.SqlProvider;
using LinqToDB.Internal.SqlQuery;
using LinqToDB.Mapping;

using NUnit.Framework;

using Shouldly;

namespace Tests.DataProvider
{
	[TestFixture]
	public class OracleSqlBuilderTests
	{
		[Table("Issue1879Table")]
		sealed class Issue1879Table
		{
			[PrimaryKey, Identity]
			public int Id { get; set; }

			[Column]
			public int Value { get; set; }
		}

		[Table("Issue1879SequenceTable")]
		sealed class Issue1879SequenceTable
		{
			[PrimaryKey]
			[SequenceName("Issue1879Seq")]
			public int Id { get; set; }

			[Column]
			public int Value { get; set; }
		}

		[Table("Issue1879NullableTable")]
		sealed class Issue1879NullableTable
		{
			[Column, Identity]
			public int? Id { get; set; }

			[Column]
			public int Value { get; set; }
		}

		// Oracle's identity clause implies NOT NULL and rejects a conflicting inline constraint, so the null
		// attribute that follows it must not come out as NULL even for a Nullable<T> member.
		[Test]
		public void Issue1879NullableIdentityIsNotNullForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlCreateTableStatement(table), entityType: typeof(Issue1879NullableTable));

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("GENERATED BY DEFAULT AS IDENTITY NOT NULL");
		}

		[Test]
		public void Issue1879CreateTableKeepsSequenceIdentityWhenSequenceNameIsSet()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlCreateTableStatement(table), entityType: typeof(Issue1879SequenceTable));

			sql.Count.ShouldBe(3);
			sql[0].ShouldNotContain("GENERATED BY DEFAULT AS IDENTITY");
			sql[1].ShouldContain("CREATE SEQUENCE \"Issue1879Seq\"");
			sql[2].ShouldContain("CREATE OR REPLACE TRIGGER \"TIDENTITY_Issue1879SequenceTable\"");
			sql[2].ShouldContain("\"Issue1879Seq\".NEXTVAL");
			sql[2].ShouldContain("IF :NEW.\"Id\" IS NULL THEN");
		}

		[Test]
		public void Issue1879DropTableDropsSequenceAndTriggerWhenSequenceNameIsSet()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlDropTableStatement(table), entityType: typeof(Issue1879SequenceTable));

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("DROP TRIGGER \"TIDENTITY_Issue1879SequenceTable\"");
			sql[0].ShouldContain("DROP SEQUENCE \"Issue1879Seq\"");
			sql[0].ShouldContain("DROP TABLE \"Issue1879SequenceTable\"");
		}

		[Test]
		public void Issue1879TruncateResetsSequenceWhenSequenceNameIsSet()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlTruncateTableStatement
			{
				Table         = table,
				ResetIdentity = true,
			}, entityType: typeof(Issue1879SequenceTable));

			sql.Count.ShouldBe(2);
			sql[0].ShouldBe("TRUNCATE TABLE \"Issue1879SequenceTable\"");
			sql[1].ShouldNotContain("GENERATED");
			sql[1].ShouldContain("ALTER SEQUENCE \"Issue1879Seq\"");
		}

		[Test]
		public void Issue1879CreateTableUsesNativeIdentityForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlCreateTableStatement(table));

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("GENERATED BY DEFAULT AS IDENTITY");
			sql[0].ShouldNotContain("SIDENTITY_");
			sql[0].ShouldNotContain("TIDENTITY_");
		}

		[Test]
		public void Issue1879CreateTableKeepsSequenceIdentityForOracle11()
		{
			var sql = BuildSql(OracleVersion.v11, table => new SqlCreateTableStatement(table));

			sql.Count.ShouldBe(3);
			sql[0].ShouldNotContain("GENERATED BY DEFAULT AS IDENTITY");
			sql[1].ShouldContain("CREATE SEQUENCE \"SIDENTITY_Issue1879Table\"");
			sql[2].ShouldContain("CREATE OR REPLACE TRIGGER \"TIDENTITY_Issue1879Table\"");
			sql[2].ShouldNotContain("IS NULL THEN");
		}

		[Test]
		public void Issue1879DropTableDoesNotDropSequenceOrTriggerForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlDropTableStatement(table));

			sql.ShouldBe(new[] { "DROP TABLE \"Issue1879Table\"" });
		}

		[Test]
		public void Issue1879DropTableIfExistsDoesNotDropSequenceOrTriggerForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlDropTableStatement(table), TableOptions.DropIfExists);

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("DROP TABLE \"Issue1879Table\"");
			sql[0].ShouldNotContain("SIDENTITY_");
			sql[0].ShouldNotContain("TIDENTITY_");
		}

		[Test]
		public void Issue1879DropTableDropsSequenceAndTriggerForOracle11()
		{
			var sql = BuildSql(OracleVersion.v11, table => new SqlDropTableStatement(table));

			sql.Count.ShouldBe(1);
			sql[0].ShouldContain("DROP TRIGGER \"TIDENTITY_Issue1879Table\"");
			sql[0].ShouldContain("DROP SEQUENCE \"SIDENTITY_Issue1879Table\"");
			sql[0].ShouldContain("DROP TABLE \"Issue1879Table\"");
		}

		[Test]
		public void Issue1879TruncateResetsNativeIdentityForOracle12()
		{
			var sql = BuildSql(OracleVersion.v12, table => new SqlTruncateTableStatement
			{
				Table         = table,
				ResetIdentity = true,
			});

			sql.ShouldBe(new[]
			{
				"TRUNCATE TABLE \"Issue1879Table\"",
				"ALTER TABLE \"Issue1879Table\" MODIFY (\"Id\" GENERATED BY DEFAULT AS IDENTITY (START WITH 1))",
			});
		}

		static IReadOnlyList<string> BuildSql(
			OracleVersion                version,
			Func<SqlTable, SqlStatement> createStatement,
			TableOptions                 tableOptions = TableOptions.NotSet,
			Type?                        entityType   = null)
		{
			var provider  = OracleTools.GetDataProvider(version, OracleProvider.Managed);
			var options   = new DataOptions();
			var optimizer = provider.GetSqlOptimizer(options);
			var factory   = optimizer.CreateSqlExpressionFactory(provider.MappingSchema, options);
			var context   = new OptimizationContext(
				new EvaluationContext(),
				options,
				provider.SqlProviderFlags,
				provider.MappingSchema,
				optimizer.CreateOptimizerVisitor(false),
				optimizer.CreateConvertVisitor(false),
				factory,
				false,
				true,
				static () => NoopQueryParametersNormalizer.Instance);
			var builder   = provider.CreateSqlBuilder(provider.MappingSchema, options);
			var table     = new SqlTable(provider.MappingSchema.GetEntityDescriptor(entityType ?? typeof(Issue1879Table)))
			{
				TableOptions = tableOptions,
			};
			var statement = createStatement(table);
			var commands  = new List<string>();

			for (var commandNumber = 0; commandNumber < builder.CommandCount(statement); commandNumber++)
			{
				var sql = new StringBuilder();
				builder.BuildSql(commandNumber, statement, sql, context, new AliasesContext(), null);
				commands.Add(sql.ToString().Trim());
			}

			return commands;
		}
	}
}
