// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.Firebird
{
	[Table("CamelCaseName")]
	public class CamelCaseName
	{
		[Column("Id"    , IsPrimaryKey = true)] public int     Id    { get; set; } // integer
		[Column("NAME1"                      )] public string? Name1 { get; set; } // varchar(20)
		[Column("Name2"                      )] public string? Name2 { get; set; } // varchar(20)
		[Column("NAME3"                      )] public string? Name3 { get; set; } // varchar(20)
		[Column("_NAME4"                     )] public string? Name4 { get; set; } // varchar(20)
		[Column("NAME 5"                     )] public string? Name5 { get; set; } // varchar(20)
	}
}
