configuration: Release

environment:
  packageVersion: 1.9.0
  linq2dbVersion: 1.9.0

version: $(packageVersion).{build}

cache:
- packages -> **\packages.config

init:
- cmd: git config --global core.autocrlf true
- ps: |
    if ($env:APPVEYOR_REPO_BRANCH -ne "release") 
    {
        $env:packageVersion = "$env:packageVersion-rc$env:appveyor_build_number"
    }


nuget:
  account_feed: false
  project_feed: false

build:
  project: T4Models.sln
  publish_nuget: false
  verbosity: minimal

after_build:
- cmd: cd NuGet
- cmd: PackAV.bat %packageVersion% %linq2dbVersion%
- cmd: cd ..


artifacts:
- path: NuGet\*.nupkg


deploy:
- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: oTYw2IwTnz4qMD8c/MR/6mo+Nx3wa5Pp8MYfsKBCKCVuU6QCHlj+6QMXpnQses8G
  on:
    branch: release

skip_commits:
  message: /ci skip./      # Regex for matching commit message
