// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Fluent.SqlServerNorthwind
{
	public class Category
	{
		public int     CategoryId   { get; set; } // int
		public string  CategoryName { get; set; } = null!; // nvarchar(15)
		public string? Description  { get; set; } // ntext
		public byte[]? Picture      { get; set; } // image

		#region Associations
		/// <summary>
		/// FK_Products_Categories backreference
		/// </summary>
		public IEnumerable<Product> Products { get; set; } = null!;
		#endregion
	}
}
