// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.SQLiteNorthwind
{
	[Table("Products")]
	public class Product
	{
		[Column("ProductID"      , IsPrimaryKey = true )] public int     ProductId       { get; set; } // int
		[Column("ProductName"    , CanBeNull    = false)] public string  ProductName     { get; set; } = null!; // varchar(40)
		[Column("SupplierID"                           )] public int?    SupplierId      { get; set; } // int
		[Column("CategoryID"                           )] public int?    CategoryId      { get; set; } // int
		[Column("QuantityPerUnit"                      )] public string? QuantityPerUnit { get; set; } // varchar(20)
		[Column("UnitPrice"                            )] public double? UnitPrice       { get; set; } // float
		[Column("UnitsInStock"                         )] public int?    UnitsInStock    { get; set; } // int
		[Column("UnitsOnOrder"                         )] public int?    UnitsOnOrder    { get; set; } // int
		[Column("ReorderLevel"                         )] public int?    ReorderLevel    { get; set; } // int
		[Column("Discontinued"                         )] public int     Discontinued    { get; set; } // int
	}
}
