name: "🪳 Bug Report: CLI Tool"
description: Linq To DB CLI scaffold tool bug report
labels: ["status: needs-tests", "area: scaffold"]
type: Bug
body:
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Describe your issue.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Include minimal steps to reproduce the problem. E.g.:
        * anonymized command line and/or configuration file
        * scaffold interceptor code
        * database schema script fragment causing issues during scaffold
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error details
      description: |
        If you observe error, provide full error message including exception stack if any.
      placeholder: Expected behavior
    validations:
      required: false
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        If it worked in previous Linq To DB CLI releases, provide latest release version where it worked before.
      placeholder: Regression?
    validations:
      required: false
  - type: input
    attributes:
      label: Linq To DB CLI version
      description: |
        [linq2db.cli](https://www.nuget.org/packages/linq2db.cli) nuget version
      placeholder: e.g. 5.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: .NET version
      description: |
        .NET version
      placeholder: e.g. 9.0.2
    validations:
      required: true
  - type: input
    attributes:
      label: Database
      description: |
        Database including version
      placeholder: SQL Server 2022
    validations:
      required: false
  - type: input
    attributes:
      label: Operating system
      description: |
        Operating system type (Windows, Linux or macOS)
      placeholder: Windows
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Additional environment details
      placeholder: Configuration
    validations:
      required: false
