// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------


#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.NoMetadata.SQLiteNorthwind
{
	public class AlphabeticalListOfProduct
	{
		public int     ProductId       { get; set; } // INT
		public string  ProductName     { get; set; } = null!; // varchar(40)
		public int?    SupplierId      { get; set; } // INT
		public int?    CategoryId      { get; set; } // INT
		public string? QuantityPerUnit { get; set; } // varchar(20)
		public double? UnitPrice       { get; set; } // float(26)
		public int?    UnitsInStock    { get; set; } // INT
		public int?    UnitsOnOrder    { get; set; } // INT
		public int?    ReorderLevel    { get; set; } // INT
		public int     Discontinued    { get; set; } // INT
		public string  CategoryName    { get; set; } = null!; // varchar(15)
	}
}
