// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using IBM.Data.DB2Types;
using LinqToDB;
using LinqToDB.Mapping;
using LinqToDB.Tools.Comparers;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.All.DB2
{
	[Table("InheritanceChild")]
	public class InheritanceChild : IEquatable<InheritanceChild>
	{
		[Column("InheritanceChildId" , DataType = DataType.Int32  , DbType = "INTEGER"    , IsPrimaryKey = true)] public DB2Int32   InheritanceChildId  { get; set; } // INTEGER
		[Column("InheritanceParentId", DataType = DataType.Int32  , DbType = "INTEGER"                         )] public DB2Int32   InheritanceParentId { get; set; } // INTEGER
		[Column("TypeDiscriminator"  , DataType = DataType.Int32  , DbType = "INTEGER"                         )] public DB2Int32?  TypeDiscriminator   { get; set; } // INTEGER
		[Column("Name"               , DataType = DataType.VarChar, DbType = "VARCHAR(50)", Length       = 50  )] public DB2String? Name                { get; set; } // VARCHAR(50)

		#region IEquatable<T> support
		private static readonly IEqualityComparer<InheritanceChild> _equalityComparer = ComparerBuilder.GetEqualityComparer<InheritanceChild>(c => c.InheritanceChildId);

		public bool Equals(InheritanceChild? other)
		{
			return _equalityComparer.Equals(this, other!);
		}

		public override int GetHashCode()
		{
			return _equalityComparer.GetHashCode(this);
		}

		public override bool Equals(object? obj)
		{
			return Equals(obj as InheritanceChild);
		}
		#endregion
	}
}
