// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.NoMetadata.Access.Both
{
	public class DataTypeTest
	{
		public int       DataTypeId { get; set; } // COUNTER
		public byte[]?   Binary     { get; set; } // LongBinary
		public int?      Boolean    { get; set; } // Long
		public byte?     Byte       { get; set; } // Byte
		public byte[]?   Bytes      { get; set; } // LongBinary
		public char?     Char       { get; set; } // VarChar(1)
		public DateTime? DateTime   { get; set; } // DateTime
		public decimal?  Decimal    { get; set; } // Currency
		public double?   Double     { get; set; } // Double
		public Guid?     Guid       { get; set; } // GUID
		public short?    Int16      { get; set; } // Short
		public int?      Int32      { get; set; } // Long
		public int?      Int64      { get; set; } // Long
		public decimal?  Money      { get; set; } // Currency
		public byte?     SByte      { get; set; } // Byte
		public float?    Single     { get; set; } // Single
		public byte[]?   Stream     { get; set; } // LongBinary
		public string?   String     { get; set; } // VarChar(50)
		public short?    UInt16     { get; set; } // Short
		public int?      UInt32     { get; set; } // Long
		public int?      UInt64     { get; set; } // Long
		public string?   Xml        { get; set; } // LongText
	}
}
