// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.SqlServerNorthwind
{
	[Table("Categories")]
	public class Category
	{
		[Column("CategoryID"  , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     CategoryId   { get; set; } // int
		[Column("CategoryName", CanBeNull    = false                                                             )] public string  CategoryName { get; set; } = null!; // nvarchar(15)
		[Column("Description"                                                                                    )] public string? Description  { get; set; } // ntext
		[Column("Picture"                                                                                        )] public byte[]? Picture      { get; set; } // image

		#region Associations
		/// <summary>
		/// FK_Products_Categories backreference
		/// </summary>
		[Association(ThisKey = nameof(CategoryId), OtherKey = nameof(Product.CategoryId))]
		public IEnumerable<Product> Products { get; set; } = null!;
		#endregion
	}
}
