// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.SqlServerNorthwind
{
	[Table("Orders Qry", IsView = true)]
	public class OrdersQry
	{
		[Column("OrderID"                          )] public int       OrderId        { get; set; } // int
		[Column("CustomerID"                       )] public string?   CustomerId     { get; set; } // nchar(5)
		[Column("EmployeeID"                       )] public int?      EmployeeId     { get; set; } // int
		[Column("OrderDate"                        )] public DateTime? OrderDate      { get; set; } // datetime
		[Column("RequiredDate"                     )] public DateTime? RequiredDate   { get; set; } // datetime
		[Column("ShippedDate"                      )] public DateTime? ShippedDate    { get; set; } // datetime
		[Column("ShipVia"                          )] public int?      ShipVia        { get; set; } // int
		[Column("Freight"                          )] public decimal?  Freight        { get; set; } // money
		[Column("ShipName"                         )] public string?   ShipName       { get; set; } // nvarchar(40)
		[Column("ShipAddress"                      )] public string?   ShipAddress    { get; set; } // nvarchar(60)
		[Column("ShipCity"                         )] public string?   ShipCity       { get; set; } // nvarchar(15)
		[Column("ShipRegion"                       )] public string?   ShipRegion     { get; set; } // nvarchar(15)
		[Column("ShipPostalCode"                   )] public string?   ShipPostalCode { get; set; } // nvarchar(10)
		[Column("ShipCountry"                      )] public string?   ShipCountry    { get; set; } // nvarchar(15)
		[Column("CompanyName"   , CanBeNull = false)] public string    CompanyName    { get; set; } = null!; // nvarchar(40)
		[Column("Address"                          )] public string?   Address        { get; set; } // nvarchar(60)
		[Column("City"                             )] public string?   City           { get; set; } // nvarchar(15)
		[Column("Region"                           )] public string?   Region         { get; set; } // nvarchar(15)
		[Column("PostalCode"                       )] public string?   PostalCode     { get; set; } // nvarchar(10)
		[Column("Country"                          )] public string?   Country        { get; set; } // nvarchar(15)
	}
}
