// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.Access.OleDb
{
	[Table("Scalar_DataReader", IsView = true)]
	public class ScalarDataReader
	{
		[Column("intField"   )] public int?    IntField    { get; set; } // Long
		[Column("stringField")] public string? StringField { get; set; } // LongText
	}
}
