// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using LinqToDB.Tools.Comparers;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.All.Ydb
{
	[Table("Child")]
	public class Child : IEquatable<Child>
	{
		[Column("ParentID", DataType = DataType.Int32, DbType = "Int32"                     )] public int ParentId { get; set; } // Int32
		[Column("ChildID" , DataType = DataType.Int32, DbType = "Int32", IsPrimaryKey = true)] public int ChildId  { get; set; } // Int32

		#region IEquatable<T> support
		private static readonly IEqualityComparer<Child> _equalityComparer = ComparerBuilder.GetEqualityComparer<Child>(c => c.ChildId);

		public bool Equals(Child? other)
		{
			return _equalityComparer.Equals(this, other!);
		}

		public override int GetHashCode()
		{
			return _equalityComparer.GetHashCode(this);
		}

		public override bool Equals(object? obj)
		{
			return Equals(obj as Child);
		}
		#endregion
	}
}
