// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using LinqToDB.Tools.Comparers;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.All.Informix
{
	[Table("doctor")]
	public class Doctor : IEquatable<Doctor>
	{
		[Column("personid", DataType  = DataType.Int32, DbType   = "INTEGER"        , Length = 0             , IsPrimaryKey = true)] public int    Personid { get; set; } // INTEGER
		[Column("taxonomy", CanBeNull = false         , DataType = DataType.NVarChar, DbType = "NVARCHAR(50)", Length       = 50  )] public string Taxonomy { get; set; } = null!; // NVARCHAR(50)

		#region IEquatable<T> support
		private static readonly IEqualityComparer<Doctor> _equalityComparer = ComparerBuilder.GetEqualityComparer<Doctor>(c => c.Personid);

		public bool Equals(Doctor? other)
		{
			return _equalityComparer.Equals(this, other!);
		}

		public override int GetHashCode()
		{
			return _equalityComparer.GetHashCode(this);
		}

		public override bool Equals(object? obj)
		{
			return Equals(obj as Doctor);
		}
		#endregion

		#region Associations
		/// <summary>
		/// FK_doctor_person
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(Personid), OtherKey = nameof(Informix.Person.Personid))]
		public Person Person { get; set; } = null!;
		#endregion
	}
}
