// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.PostgreSQL
{
	[Table("multitenant_table")]
	public class MultitenantTable
	{
		[Column("tenantid"   , SkipOnUpdate = true)] public Guid     Tenantid    { get; set; } // uuid
		[Column("id"         , SkipOnUpdate = true)] public Guid     Id          { get; set; } // uuid
		[Column("name"       , SkipOnUpdate = true)] public string?  Name        { get; set; } // character varying(100)
		[Column("description", SkipOnUpdate = true)] public string?  Description { get; set; } // text
		[Column("createdat"  , SkipOnUpdate = true)] public DateTime Createdat   { get; set; } // timestamp (6) without time zone
	}
}
