// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Default.PostgreSQL
{
	/// <summary>
	/// This is the Person table
	/// </summary>
	[Table("Person")]
	public class Person
	{
		/// <summary>
		/// This is the Person.PersonID column
		/// </summary>
		[Column("PersonID"  , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     PersonId   { get; set; } // integer
		[Column("FirstName" , CanBeNull    = false                                                             )] public string  FirstName  { get; set; } = null!; // character varying(50)
		[Column("LastName"  , CanBeNull    = false                                                             )] public string  LastName   { get; set; } = null!; // character varying(50)
		[Column("MiddleName"                                                                                   )] public string? MiddleName { get; set; } // character varying(50)
		[Column("Gender"                                                                                       )] public char    Gender     { get; set; } // character(1)

		#region Associations
		/// <summary>
		/// Doctor_PersonID_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(PersonId), OtherKey = nameof(Doctor.PersonId))]
		public Doctor? DoctorPersonIDfkey { get; set; }

		/// <summary>
		/// Patient_PersonID_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(PersonId), OtherKey = nameof(Patient.PersonId))]
		public Patient? PatientPersonIDfkey { get; set; }
		#endregion
	}
}
