// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using LinqToDB.Tools.Comparers;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;

#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.All.SqlServerNorthwind
{
	[Table("CustomerCustomerDemo")]
	public class CustomerCustomerDemo : IEquatable<CustomerCustomerDemo>
	{
		[Column("CustomerID"    , DataType = DataType.NChar, DbType = "nchar(5)" , Length = 5 , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public SqlString CustomerId     { get; set; } // nchar(5)
		[Column("CustomerTypeID", DataType = DataType.NChar, DbType = "nchar(10)", Length = 10, IsPrimaryKey = true, PrimaryKeyOrder = 1)] public SqlString CustomerTypeId { get; set; } // nchar(10)

		#region IEquatable<T> support
		private static readonly IEqualityComparer<CustomerCustomerDemo> _equalityComparer = ComparerBuilder.GetEqualityComparer<CustomerCustomerDemo>(c => c.CustomerId, c => c.CustomerTypeId);

		public bool Equals(CustomerCustomerDemo? other)
		{
			return _equalityComparer.Equals(this, other!);
		}

		public override int GetHashCode()
		{
			return _equalityComparer.GetHashCode(this);
		}

		public override bool Equals(object? obj)
		{
			return Equals(obj as CustomerCustomerDemo);
		}
		#endregion

		#region Associations
		/// <summary>
		/// FK_CustomerCustomerDemo
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CustomerTypeId), OtherKey = nameof(CustomerDemographic.CustomerTypeId))]
		public CustomerDemographic FkCustomerCustomerDemo { get; set; } = null!;

		/// <summary>
		/// FK_CustomerCustomerDemo_Customers
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CustomerId), OtherKey = nameof(Customer.CustomerId))]
		public Customer Customers { get; set; } = null!;
		#endregion
	}
}
