// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------


#pragma warning disable 1573, 1591
#nullable enable

namespace Cli.Fluent.Ydb
{
	public class AllType
	{
		public int     Id               { get; set; } // Int32
		public int?    IntDataType      { get; set; } // Int32
		public short?  SmallintDataType { get; set; } // Int16
		public float?  FloatDataType    { get; set; } // Float
		public double? DoubleDataType   { get; set; } // Double
		public byte[]? NcharDataType    { get; set; } // Bytes
		public byte[]? Char20DataType   { get; set; } // Bytes
		public byte[]? VarcharDataType  { get; set; } // Bytes
		public byte[]? CharDataType     { get; set; } // Bytes
		public bool?   BitDataType      { get; set; } // Bool
	}
}
